#!/bin/bash
################################################################################
# Forge v19 — Initialize any repo with the 8-department structure
#
# Usage: ./init-repo-forge.sh <repo-path> [--force]
#
# Creates:
#   scripts/councils/department-council.sh
#   scripts/forge/                (symlink to mon-ipad/scripts/forge/)
#   data/departments/             (8 council JSON files + metrics dirs)
#   data/metrics/                 (aggregated metrics)
#   Updated CLAUDE.md             (adds Forge v19 section)
#
# Inspired by: Paperclip (org charts), Karpathy autoresearch (5-min loops)
################################################################################

set -euo pipefail

FORGE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MON_IPAD="/home/lahargnedebartoli/mon-ipad"
REPO_PATH="${1:-}"
FORCE="${2:-}"

ts() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }

if [ -z "$REPO_PATH" ]; then
    echo "Usage: $0 <repo-path> [--force]"
    echo ""
    echo "Available repos:"
    for d in /home/lahargnedebartoli/*/; do
        [ -d "$d/.git" ] && echo "  $(basename $d)"
    done
    exit 1
fi

# Resolve path
if [[ "$REPO_PATH" != /* ]]; then
    REPO_PATH="/home/lahargnedebartoli/$REPO_PATH"
fi

if [ ! -d "$REPO_PATH/.git" ]; then
    echo "ERROR: Not a git repo: $REPO_PATH"
    exit 1
fi

REPO_NAME="$(basename "$REPO_PATH")"
echo "================================================"
echo "  Forge v19 — Initializing: $REPO_NAME"
echo "  Path: $REPO_PATH"
echo "  Time: $(ts)"
echo "================================================"

# ── 1. Create directory structure ──────────────────────────────────────

echo "[1/6] Creating directory structure..."
DEPARTMENTS="research engineering evolution product business evaluation infra finance"

mkdir -p "$REPO_PATH/scripts/councils"
mkdir -p "$REPO_PATH/data/metrics"

for dept in $DEPARTMENTS; do
    mkdir -p "$REPO_PATH/data/departments/$dept"
done

# ── 2. Create council JSON files ───────────────────────────────────────

echo "[2/6] Creating council state files..."
for dept in $DEPARTMENTS; do
    COUNCIL_FILE="$REPO_PATH/data/departments/council-${dept}.json"
    if [ ! -f "$COUNCIL_FILE" ] || [ "$FORCE" = "--force" ]; then
        cat > "$COUNCIL_FILE" << JSONEOF
{
  "dept": "$dept",
  "repo": "$REPO_NAME",
  "iteration": 0,
  "best_metric": null,
  "last_run": null,
  "created": "$(ts)",
  "forge_version": "v19",
  "history": []
}
JSONEOF
        echo "  Created: council-${dept}.json"
    else
        echo "  Exists: council-${dept}.json (use --force to overwrite)"
    fi
done

# ── 3. Create department council runner ────────────────────────────────

echo "[3/6] Creating council runner script..."
COUNCIL_SCRIPT="$REPO_PATH/scripts/councils/department-council.sh"
cat > "$COUNCIL_SCRIPT" << 'SCRIPTEOF'
#!/bin/bash
################################################################################
# Department Council Runner — Karpathy loop per department
# Generated by Forge v19 init-repo-forge.sh
# Usage: department-council.sh <dept> [--dry-run]
################################################################################

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FORGE_COUNCIL="$REPO_ROOT/scripts/forge/council-template.py"
DEPT="${1:-}"
DRY_RUN="${2:-}"

source "$REPO_ROOT/.env.local" 2>/dev/null || true
source "/home/lahargnedebartoli/mon-ipad/.env.local" 2>/dev/null || true

if [ -z "$DEPT" ]; then
    echo "Usage: $0 <department> [--dry-run]"
    echo "Departments: research engineering evolution product business evaluation infra finance"
    exit 1
fi

# Use shared forge council from mon-ipad if local doesn't exist
if [ ! -f "$FORGE_COUNCIL" ]; then
    FORGE_COUNCIL="/home/lahargnedebartoli/mon-ipad/scripts/forge/council-template.py"
fi

ARGS="--repo $REPO_ROOT --dept $DEPT"
[ "$DRY_RUN" = "--dry-run" ] && ARGS="$ARGS --dry-run"

exec python3 "$FORGE_COUNCIL" $ARGS
SCRIPTEOF
chmod +x "$COUNCIL_SCRIPT"

# ── 4. Symlink forge tools ─────────────────────────────────────────────

echo "[4/6] Linking forge tools..."
FORGE_LINK="$REPO_PATH/scripts/forge"
if [ -L "$FORGE_LINK" ] || [ -d "$FORGE_LINK" ]; then
    echo "  Forge dir already exists"
else
    ln -s "$MON_IPAD/scripts/forge" "$FORGE_LINK"
    echo "  Symlinked: scripts/forge → mon-ipad/scripts/forge"
fi

# ── 5. Create guardian report ──────────────────────────────────────────

echo "[5/6] Creating guardian report..."
GUARDIAN_FILE="$REPO_PATH/data/departments/guardian-report.json"
cat > "$GUARDIAN_FILE" << JSONEOF
{
  "repo": "$REPO_NAME",
  "forge_version": "v19",
  "initialized": "$(ts)",
  "departments": 8,
  "layers": 3,
  "status": "INITIALIZED",
  "departments_list": [
    {"id": "D1", "name": "research", "layer": "L2", "status": "NEW"},
    {"id": "D2", "name": "engineering", "layer": "L2", "status": "NEW"},
    {"id": "D3", "name": "evolution", "layer": "L2", "status": "NEW"},
    {"id": "D4", "name": "product", "layer": "L2", "status": "NEW"},
    {"id": "D5", "name": "business", "layer": "L2", "status": "NEW"},
    {"id": "D6", "name": "evaluation", "layer": "L2", "status": "NEW"},
    {"id": "D7", "name": "infra", "layer": "L3", "status": "NEW"},
    {"id": "D8", "name": "finance", "layer": "L3", "status": "NEW"}
  ]
}
JSONEOF

# ── 6. Update CLAUDE.md ───────────────────────────────────────────────

echo "[6/6] Updating CLAUDE.md with Forge v19 section..."
FORGE_SECTION="

## Forge v19 — 3 Layers × 8 Departments ($(ts))

\`\`\`
L1 STRATEGIC:  Claude Code CLI + User (vision, milestones, decisions)
L2 APPLICATION: D1 Research | D2 Engineering | D3 Evolution | D4 Product | D5 Business | D6 Evaluation
L3 LOGISTICS:   D7 Infra | D8 Finance
\`\`\`

Each department runs a Karpathy autoresearch loop:
- SCAN → PROPOSE → EXECUTE (5-min) → EVALUATE → KEEP/REVERT
- Council state: data/departments/council-<dept>.json
- Metrics log: data/departments/<dept>/metrics.jsonl
- Runner: scripts/councils/department-council.sh <dept>

Shared infra: VM (control tower) + Laptop (local models) + HF Spaces (3 accounts) + GPU burst
"

if grep -q "Forge v19" "$REPO_PATH/CLAUDE.md" 2>/dev/null; then
    echo "  CLAUDE.md already has Forge v19 section"
else
    echo "$FORGE_SECTION" >> "$REPO_PATH/CLAUDE.md"
    echo "  Appended Forge v19 section to CLAUDE.md"
fi

echo ""
echo "================================================"
echo "  Forge v19 initialized for: $REPO_NAME"
echo "  Departments: 8 | Layers: 3"
echo "  Run councils: scripts/councils/department-council.sh <dept>"
echo "  Verify: python3 scripts/forge/council-template.py --repo $REPO_PATH --dept research --dry-run"
echo "================================================"
