#!/usr/bin/env python3
"""
SHA256 parity check for features/engine.py copies.

Single source of truth: hf-space/features/engine.py
Mirrors: features/engine.py (symlink, always OK), nba-quant-space/features/engine.py,
         hf-space-2/, hf-space-3/, ... (any copy under the repo).

Usage:
    python scripts/check_engine_parity.py          # check against engine.sha256.lock
    python scripts/check_engine_parity.py --write  # refresh the lock to match canonical
    python scripts/check_engine_parity.py --sync   # overwrite all mirrors from canonical

Exits 0 if all copies agree, 1 otherwise. Suitable as pre-commit hook
and CI gate.

Cycle 14 — architecture bottleneck #2 (engine monolith drift). The engine
file is 7213 LOC and was being copy-pasted by hand to 6 HF Spaces — this
catches any drift the moment it enters git.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CANONICAL = REPO / "hf-space" / "features" / "engine.py"
LOCK = REPO / "engine.sha256.lock"

# Frozen / legacy HF spaces pinned to older engine versions.
# These directories are DELIBERATELY out of sync with the canonical.
# Add to this set only after confirming the space is frozen on purpose.
FROZEN_MIRRORS: set[str] = {
    "nba-quant-space/features/engine.py",  # v3.0-37cat, pinned Apr 2026
}


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def find_mirrors() -> list[Path]:
    """Every engine.py under the repo, following no symlinks."""
    mirrors: list[Path] = []
    for p in REPO.rglob("engine.py"):
        # Skip node_modules, .git, venvs
        parts = p.parts
        if any(seg in parts for seg in (".git", "node_modules", ".venv", "venv", "__pycache__")):
            continue
        # Skip symlinks — they can't drift
        try:
            if p.is_symlink():
                continue
        except OSError:
            continue
        # Skip frozen legacy mirrors
        rel = str(p.relative_to(REPO))
        if rel in FROZEN_MIRRORS:
            continue
        mirrors.append(p)
    return sorted(mirrors)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="refresh engine.sha256.lock to match canonical")
    ap.add_argument("--sync", action="store_true", help="overwrite all mirrors from canonical (DESTRUCTIVE)")
    args = ap.parse_args()

    if not CANONICAL.exists():
        print(f"FATAL: canonical engine missing: {CANONICAL}", file=sys.stderr)
        return 1

    canon_hash = sha256(CANONICAL)
    canon_loc = sum(1 for _ in CANONICAL.open())

    if args.write:
        LOCK.write_text(
            f"# Auto-generated by scripts/check_engine_parity.py\n"
            f"# Canonical: {CANONICAL.relative_to(REPO)}\n"
            f"# LOC: {canon_loc}\n"
            f"sha256 = {canon_hash}\n"
        )
        print(f"wrote lock: {canon_hash[:16]}... ({canon_loc} LOC)")
        return 0

    mirrors = find_mirrors()
    print(f"[parity] canonical: {CANONICAL.relative_to(REPO)} sha={canon_hash[:16]}... loc={canon_loc}")
    print(f"[parity] found {len(mirrors)} engine.py file(s)")

    bad: list[tuple[Path, str, int]] = []
    for m in mirrors:
        h = sha256(m)
        loc = sum(1 for _ in m.open())
        status = "OK " if h == canon_hash else "BAD"
        rel = m.relative_to(REPO)
        print(f"  {status} {h[:16]}... loc={loc:5d}  {rel}")
        if h != canon_hash:
            bad.append((m, h, loc))

    if args.sync and bad:
        print(f"\n[parity] --sync requested, overwriting {len(bad)} mirror(s)")
        canon_bytes = CANONICAL.read_bytes()
        for m, _, _ in bad:
            m.write_bytes(canon_bytes)
            print(f"  synced {m.relative_to(REPO)}")
        return 0

    # Check against lock file too
    if LOCK.exists():
        lock_hash = None
        for line in LOCK.read_text().splitlines():
            if line.startswith("sha256 = "):
                lock_hash = line.split("=", 1)[1].strip()
                break
        if lock_hash and lock_hash != canon_hash:
            print(f"\n[parity] LOCK MISMATCH: lock={lock_hash[:16]}... canonical={canon_hash[:16]}...")
            print(f"[parity] engine.py changed but lock was not refreshed.")
            print(f"[parity] Fix: python scripts/check_engine_parity.py --write && git add engine.sha256.lock")
            return 1

    if bad:
        print(f"\n[parity] FAIL: {len(bad)} mirror(s) drifted from canonical")
        print(f"[parity] Fix: python scripts/check_engine_parity.py --sync  (overwrites mirrors)")
        print(f"[parity]      OR re-export from HF Space to hf-space/features/engine.py")
        return 1

    print("\n[parity] OK — all copies agree")
    return 0


if __name__ == "__main__":
    sys.exit(main())
